repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: CHANGELOG.md
  - id: check-ast
  - id: check-json
  - id: check-yaml
    args: [--unsafe]
  - id: check-toml
  - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy
    additional_dependencies: ['types-requests']
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.253'
  hooks:
    - id: ruff
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    